# One declaration for the whole sandboxed process: FreeBSD::Sandbox.define.
#
# It composes the pieces the other examples wire up by hand — a Casper net
# policy, a privileged resource opened up front, a privilege drop, and
# cap_enter — and runs them in the one mandatory order. The program body after
# the block runs fully sandboxed; each opened resource comes back via a typed
# accessor named after it (FreeBSD::Sandbox.<name>).
#
# Run as root (privdrop + privileged bind need it):
#   crystal build examples/casper/sandbox.cr -o /tmp/sandbox_example
#   sudo /tmp/sandbox_example

require "http/client"

require "../../src/freebsd/sandbox"
require "../../src/freebsd/casper/net"
require "../../src/freebsd/casper/integrate/dns"
require "../../src/freebsd/casper/integrate/net"

FreeBSD::Sandbox.define do
  # Drop to an unprivileged user once everything below is open.
  user "nobody"

  # system.net policy: resolve and connect to example.com:80 only.
  # `connect_dns` is the shorthand for the "let me reach this host" recipe;
  # for richer policies use `net(mode) { |b| ... }` directly.
  connect_dns "example.com", 80

  # Prime /etc/localtime before cap_enter so Time.local keeps working sandboxed.
  tz_data

  # Open a file as root (before the drop) and keep the handle for the sandbox.
  # The motivating case: a database file readable only by root. `rights:` limits
  # the fd via cap_rights_limit before cap_enter — here, read-only.
  open("hosts", File, rights: [:read, :fstat]) { File.open("/etc/hosts", "r") }

  # Bind a privileged listener as root; the fd survives into capability mode.
  # Omitting `rights:` applies DEFAULT_LISTENER_RIGHTS (accept + event-loop set);
  # pass an explicit list to narrow it, or `rights: false` to leave it open.
  bind "listener", "127.0.0.1", 8080,
    rights: [:accept, :listen, :getsockname, :event, :fcntl]
end

# ---- everything below runs sandboxed (capability mode, dropped to nobody) ----

hosts = FreeBSD::Sandbox.hosts # => File (typed accessor generated by `open`)
puts "first line of /etc/hosts (opened as root): #{hosts.gets}"

listener = FreeBSD::Sandbox.listener # => TCPServer (generated by `bind`)
puts "listener bound: #{listener.local_address}"

# Network is policy-checked through the Casper net helper.
response = HTTP::Client.get("http://example.com/")
puts "#{response.status_code} #{response.status.description}"

# An undeclared resource would be a compile error, e.g.:
#   FreeBSD::Sandbox.secrets  # => undefined method 'secrets'

# Direct file access is blocked by capability mode.
begin
  File.open("/etc/passwd", "r", &.gets)
  puts "ERROR: direct file open should have been blocked"
rescue File::Error
  puts "direct file open blocked as expected"
end
